### ISSUE TITLE
dependencies ‘rgeos’, ‘WilcoxCV’ are not available

### ISSUE THREAD

**Issue by Huiying-Xu** [ytarazona/ForesToolboxRS#5]
when i try to install the packages, there's error: dependencies ‘rgeos’, ‘WilcoxCV’ are not available. These two packages are now removed from CRAN. Could you please help with this?

**Comment by Nowosad** [comment]
Hi @Huiying-Xu -- I just updated the code. Now the rgeos and WilxocCV packages are not needed.

**Comment by Huiying-Xu** [comment]
Thanks so much! I've successfully installed it
